# Generated by Django 4.2 on 2023-04-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_pokemon_arent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='arent',
            new_name='parent',
        ),
    ]
