# Generated by Django 4.2 on 2023-04-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_rename_arent_pokemon_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_rus',
            field=models.TextField(blank=True, max_length=200, verbose_name='название рус.'),
        ),
    ]
