# Generated by Django 4.2 on 2023-04-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_remove_pokemon_title_pokemon_title_rus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title_rus',
            field=models.CharField(blank=True, max_length=200, verbose_name='название рус.'),
        ),
    ]
